### ISSUE TITLE
gcc compile error (array bounds)

### ISSUE THREAD

**Issue by smithjd15** [robertmuth/apetag#16]
The full error message is below:

g++ -Wall -Werror -Wextra -pedantic -std=c++0x -O3   -g   -c -o basic.o basic.C
In function ‘std::string StringHex(UINT32, UINT32)’,
    inlined from ‘std::string ptrstr(const VOID*)’ at basic.H:107:74,
    inlined from ‘VOID DefaultTrace()’ at basic.C:182:41:
basic.C:361:15: error: ‘void* __builtin_memset(void*, int, long unsigned int)’ forming offset [64, 4294967294] is out of the bounds [0, 64] of object ‘buffer’ with type ‘CHAR [64]’ {aka ‘char [64]’} [-Werror=array-bounds]
  361 |     buffer[i] = '0';
      |     ~~~~~~~~~~^~~~~
basic.C: In function ‘VOID DefaultTrace()’:
basic.C:341:8: note: ‘buffer’ declared here
  341 |   CHAR buffer[64];
      |        ^~~~~~
cc1plus: all warnings being treated as errors
make: *** [<builtin>: basic.o] Error 1
*** Failure: Exit code 2 ***

**Comment by smithjd15** [comment]
Comment line 361 `buffer[i] = '0';` as a workaround.

**Comment by robertmuth** [comment]
This was fix recently
