### ISSUE TITLE
Writing Binary Text Data in Tags

### ISSUE THREAD

**Issue by vrdriver** [robertmuth/apetag#25]
Hi Robert,

I've got a question about writing binary text data to tags.

In short, I'd like to be able to add a custom APE tag, and have the dates stored in HEX format.

For example, this is what I'm needing.

52 65 73 74 72 69 63 74 69 6F 6E 73 00 CF AF 00 00 D1 AF 00 00 00 00 01 00 00 00 00 7F 51 01 00 01 00 00 00 00 7F 51 01 00 01 00 00 00 00 7F 51 01 00 01 00 00 00 00 7F 51 01 00 01 00 00 00 00 7F 51 01 00 01 00 00 00 00 7F 51 01 00 01 00 00 00 00 7F 51 01 00 01 00 00 00 00 00 00 00

The tag is: Restrictions

The data after it however is the rest of the problem.
They are Delphi values of the days from 1899 DEC 30
https://www.delphibasics.co.uk/RTL.php?Name=TDateTime

00 CF AF 00 
CFAF is UNIT16 value of 45007  
Date: 20230322

00 D1 AF 00 
D1AF is UNIT16 value of 45009 
Date: 20230324

With these 2 date examples I'm sure I can figure out the rest of the data structure for the full set of tags I'm needing, but how do I add HEX values to a tag?

Thanks,
Steve

**Comment by robertmuth** [comment]
Are you trying to change the code of apetag to support that feature or just figuring out the command line  invocation?

I have not used the program myself in a while but for the latter hex escape sequences for command line args might be helpful, e.g.:
 00 CF AF 00 -> "\x00\xCF\xAF\x00"

**Comment by vrdriver** [comment]
At the moment, I haven't changed any code. I wanted to see if it could do it first. 
I'll see if the escaped values work...

**Comment by vrdriver** [comment]
After trying out different options as per the test.sh file, I didn't really get anywhere. It just saved the ASCII values in the file.

```
${APETAG} -i ${MP3_CLONE} -m update -p  "XRestrictions1"="\x00\xCF\xAF\x00"
${APETAG} -i ${MP3_CLONE} -m update -p "XRestrictions"=\x00\xCF\xAF\x00
${APETAG} -i ${MP3_CLONE} -m update -p "XRestrictions2"=\x00\xCF\xAF\x00
${APETAG} -i ${MP3_CLONE} -m update -f "XRestrictions3"=${BIN1}
```

BIN1 file contents:
`\x00\xCF\xAF\x00`

![Screen Shot 2023-03-22 at 13 18 50](https://user-images.githubusercontent.com/5615487/226784924-15aa5231-296b-4526-b4fd-8405dd9fb970.png)

**Comment by robertmuth** [comment]
I found this:

https://stackoverflow.com/questions/37228569/how-to-use-hex-escapes-in-bash-eval-string

but I would not surprise me if the zero bytes cause problems later.

I think  there is also a mechanism where you could read the tag data from a file via the "-f" flag.
See https://github.com/robertmuth/apetag/blob/master/test.sh

But since you seem to be in control of both the producer and the consumer of that tag why don't you go
with a non-binary format?

**Comment by vrdriver** [comment]
Hmm. I take a look further at the escaping and see if I can compile it on Windows as well to see if that gives different result.

I wish I was in control of the formats, as I'm trying to match the tag that comes from this program: https://stationplaylist.com/creator.html

I'm just looking for a way to script stop and start dates. If only I didn't have to be the geek tasked with it. haha

**Comment by vrdriver** [comment]
Hi Robert. Thanks for your suggestions. I think that going forward, I'll just roll my own tag program in the end and use TagLib. It'll just make the console program Windows only.  More importantly, I'll be store the data without too much fuss.

`ape_tag.SetItem(new TagLib.Ape.Item("XRestrictions", (new TagLib.ByteVector(XRestrictions_byteVector))));`


Update: Your suggestion actually did help in doing what I needed, with the use of the 0x01 characters etc.
It really pointed me in the right direction. Thanks again!
